### ISSUE TITLE
Fix spurious CI Failure

### ISSUE THREAD

**Issue by wcampbell0x2a** [wcampbell0x2a/backhand#368]
Seen in master CI run: https://github.com/wcampbell0x2a/backhand/actions/runs/6999776418/job/19039512489

```
running 3 tests
test test_non_standard_be_v4_1 ... FAILED
test test_custom_compressor ... ok
test test_non_standard_be_v4_0 ... ok

failures:

---- test_non_standard_be_v4_1 stdout ----
Fetching file squashfs_v4.nopad.unblob.bin ...[/cargo/git/checkouts/test-assets-af055f640a5e3329/ebe2e7d/src/lib.rs:137] &tfile.url = "https://wcampbell.dev/squashfs/testing/test_custom/squashfs_v4.nopad.unblob.bin"
  => Success
thread 'test_non_standard_be_v4_1' panicked at backhand-test/tests/non_standard.rs:58:10:
called `Result::unwrap()` on an `Err` value: StdIo(Custom { kind: InvalidInput, error: "corrupt deflate stream" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_non_standard_be_v4_1

test result: FAILED. 2 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.23s
```

**Comment by wcampbell0x2a** [comment]
Another: https://github.com/wcampbell0x2a/backhand/actions/runs/6938385541/job/18874024737

**Comment by wcampbell0x2a** [comment]
Related for debugging this, add a `Cross.toml` with:
```
[build.env]
passthrough = [
    "RUST_LOG",
]
```

**Comment by wcampbell0x2a** [comment]
Following bash script will run until it finds it. Maybe it's a external library problem?

```
while cargo clean && rm -rf backhand-test/test-assets && cross build --no-default-features --features gzip --target x86_64-unknown-linux-musl --release --locked --workspace && CROSS_CONTAINER_OPTS="--network host" RUST_LOG=trace cross test --workspace --release --no-default-features --features gzip --target x86_64-unknown-linux-musl --locked --features __test_unsquashfs -- --skip slow; do :; done

```

**Comment by wcampbell0x2a** [comment]
```
024-01-09T02:39:40.481824Z  INFO backhand::filesystem::writer: Writing Inodes
2024-01-09T02:39:40.481857Z TRACE backhand::metadata: time to compress
2024-01-09T02:39:40.482419Z TRACE backhand::metadata: new metadata start: 0x42
2024-01-09T02:39:40.482425Z TRACE backhand::metadata: LEN: 00
2024-01-09T02:39:40.482436Z TRACE backhand::metadata: len: 40
2024-01-09T02:39:40.482441Z  INFO backhand::filesystem::writer: Writing Dirs
2024-01-09T02:39:40.482459Z TRACE backhand::metadata: time to compress
2024-01-09T02:39:40.482983Z TRACE backhand::metadata: new metadata start: 0x42
2024-01-09T02:39:40.482995Z TRACE backhand::metadata: LEN: 00
2024-01-09T02:39:40.483000Z TRACE backhand::metadata: len: 40
2024-01-09T02:39:40.483011Z  INFO backhand::filesystem::writer: Writing Frag Lookup Table
2024-01-09T02:39:40.483045Z  INFO backhand::filesystem::writer: Writing Id Lookup Table
2024-01-09T02:39:40.483065Z  INFO backhand::filesystem::writer: Finalize Superblock and End Bytes
2024-01-09T02:39:40.483074Z  INFO backhand::filesystem::writer: Writing Padding
2024-01-09T02:39:40.483130Z  INFO backhand::filesystem::writer: Writing Superblock
2024-01-09T02:39:40.483140Z  INFO backhand::filesystem::writer: Writing Finished
2024-01-09T02:39:40.483155Z  INFO backhand::filesystem::writer: Success
2024-01-09T02:39:40.483256Z  INFO non_standard: calling from_reader
2024-01-09T02:39:40.483280Z  INFO backhand::squashfs: Reading Compression options
2024-01-09T02:39:40.483290Z  INFO backhand::squashfs: compression_options: None
2024-01-09T02:39:40.483303Z  INFO backhand::squashfs: Reading Inodes
2024-01-09T02:39:40.483317Z TRACE backhand::reader: offset: Ok(79)
2024-01-09T02:39:40.483328Z TRACE backhand::metadata: [00, 00]
2024-01-09T02:39:40.483331Z TRACE backhand::metadata: len: 0x00
2024-01-09T02:39:40.483334Z TRACE backhand::metadata: compressed
thread 'test_non_standard_be_v4_1' panicked at backhand-test/tests/non_standard.rs:58:10:
called `Result::unwrap()` on an `Err` value: StdIo(Custom { kind: InvalidInput, error: "corrupt deflate stream" })
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by wcampbell0x2a** [comment]
Closed with https://github.com/wcampbell0x2a/backhand/pull/412
